
const productivityAndCodingSites = [
    // Project Management & Collaboration
    "notion.so",
    "trello.com",
    "asana.com",
    "monday.com",
    "clickup.com",
    "slack.com",
    "basecamp.com",
    "jira.com",
    "teamwork.com",
    "confluence.com",
    "proofhub.com",
  
    // Communication & Video Calls
    "zoom.us",
    "meet.google.com",
    "calendar.google.com",
    "skype.com",
    "webex.com",
    "whereby.com",
    "discord.com",
    "microsoftteams.com",
  
    // Cloud Storage & File Sharing
    "drive.google.com",
    "dropbox.com",
    "box.com",
    "onedrive.live.com",
    "mega.io",
    "pcloud.com",
  
    // Notes & Writing
    "docs.google.com",
    "sheets.google.com",
    "slides.google.com",
    "keep.google.com",
    "evernote.com",
    "workflowy.com",
    "bear.app",
    "simplenote.com",
    "goodnotes.com",
    "zotero.org",
  
    // Task & Time Management
    "todoist.com",
    "ticktick.com",
    "microsoft.com/en-us/microsoft-365/onenote",
    "pomofocus.io",
    "rescuetime.com",
    "focusmate.com",
    "clockify.me",
    "toggl.com",
    "forestapp.cc",
  
    // Learning & Research
    "coursera.org",
    "udemy.com",
    "khanacademy.org",
    "edx.org",
    "brilliant.org",
    "duolingo.com",
    "skillshare.com",
    "lynda.com",
    "mitopencourseware.org",
    "futurelearn.com",
    "openai.com/research",
    "arxiv.org",
  
    // AI & Research Tools
    "chat.openai.com",
    "bard.google.com",
    "perplexity.ai",
    "phind.com",
    "wolframalpha.com",
    "deepl.com",
    "grammarly.com",
    "hemingwayapp.com",
  
    // Coding & Developer Platforms
    "github.com",
    "gitlab.com",
    "bitbucket.org",
    "codepen.io",
    "jsfiddle.net",
    "replit.com",
    "stackblitz.com",
    "codesandbox.io",
    "glitch.com",
    "leetcode.com",
    "codewars.com",
    "hackerrank.com",
    "topcoder.com",
    "geeksforgeeks.org",
    "dev.to",
    "hashnode.com",
    "stackoverflow.com",
    "w3schools.com",
    "mdn.dev",
    "freecodecamp.org",
    "pluralsight.com",
  
    // API & Documentation
    "postman.com",
    "rapidapi.com",
    "swagger.io",
    "devdocs.io",
    "jsonplaceholder.typicode.com",
    "mockaroo.com",
    "reqres.in",
  
    // Cloud & DevOps
    "aws.amazon.com",
    "cloud.google.com",
    "azure.microsoft.com",
    "netlify.com",
    "vercel.com",
    "heroku.com",
    "firebase.google.com",
    "render.com",
    "railway.app",
    "supabase.com",
    "digitalocean.com",
    "linode.com",
    "kubernetes.io",
    "docker.com",
  
    // Miscellaneous Productivity
    "canva.com",
    "miro.com",
    "figma.com",
    "loom.com",
    "smallpdf.com",
    "pdfescape.com",
    "ilovepdf.com",
    "tinywow.com",
    "remove.bg",
    "unsplash.com",
    "pexels.com",
    "pixabay.com"
  ];

const unproductiveSites = [
    // Social Media & Microblogging
    "youtube.com",
    "x.com",
    "facebook.com",
    "instagram.com",
    "tiktok.com",
    "reddit.com",
    "pinterest.com",
    "snapchat.com",
    "tumblr.com",
    "discord.com",
    "twitch.tv",
    "telegram.org",
    "whatsapp.com",
    "threads.net",
    "weibo.com",
    "mastodon.social",
    "quora.com",
    "vk.com",
    "medium.com",
    "onlyfans.com",
  
    // Meme & Funny Content
    "9gag.com",
    "imgur.com",
    "ifunny.co",
    "memedroid.com",
    "knowyourmeme.com",
    "cheezburger.com",
    "thechive.com",
    "quickmeme.com",
    "funnyjunk.com",
  
    // Streaming & Video Content
    "netflix.com",
    "hulu.com",
    "disneyplus.com",
    "hbomax.com",
    "primevideo.com",
    "peacocktv.com",
    "crunchyroll.com",
    "funimation.com",
    "tubitv.com",
    "vimeo.com",
    "dailymotion.com",
    "bilibili.com",
  
    // Gaming & Game Streaming
    "roblox.com",
    "minecraft.net",
    "fortnite.com",
    "epicgames.com",
    "steampowered.com",
    "store.steampowered.com",
    "xbox.com",
    "playstation.com",
    "ea.com",
    "rockstargames.com",
    "ubisoft.com",
    "riotgames.com",
    "leagueoflegends.com",
    "chess.com",
    "lichess.org",
    "pogo.com",
    "miniclip.com",
    "addictinggames.com",
    "newgrounds.com",
    "kongregate.com",
    "armorgames.com",
  
    // Shopping & E-commerce
    "amazon.com",
    "ebay.com",
    "aliexpress.com",
    "temu.com",
    "etsy.com",
    "walmart.com",
    "target.com",
    "bestbuy.com",
    "newegg.com",
    "shein.com",
    "zalando.com",
    "stockx.com",
    "goat.com",
    "wish.com",
  
    // Gossip, Celebrities & News
    "tmz.com",
    "perezhilton.com",
    "buzzfeed.com",
    "huffpost.com",
    "dailymail.co.uk",
    "theonion.com",
    "uproxx.com",
    "eonline.com",
    "usmagazine.com",
    "vanityfair.com",
    "gawker.com",
  
    // Dating & Social Discovery
    "tinder.com",
    "bumble.com",
    "hinge.co",
    "okcupid.com",
    "plentyoffish.com",
    "match.com",
    "grindr.com",
    "coffeemeetsbagel.com",
    "happn.com",
  
    // Forums & Discussion Boards
    "4chan.org",
    "8kun.top",
    "f95zone.to",
    "gtaforums.com",
    "resetera.com",
    "neogaf.com",
    "slickdeals.net",
    "blackhatworld.com",
  
    // Random & Useless Websites
    "theuselessweb.com",
    "pointerpointer.com",
    "thisiswhyimbroke.com",
    "eelslap.com",
    "cat-bounce.com",
    "hackertyper.com",
    "corndog.io",
    "paper-io.com",
    "agar.io",
    "slither.io"
  ];
  

export {productivityAndCodingSites, unproductiveSites}